---
driver_config:
 openstack_username: <%= ENV['OS_USERNAME'] %>
 openstack_api_key: <%= ENV['OS_PASSWORD'] %>
 openstack_auth_url: <%= ENV['OS_AUTH_URL'] %>/tokens
 openstack_tenant: <%= ENV['OS_TENANT_NAME'] %>
 key_name: <%= ENV['KEY_NAME'] %>
 floating_ip_pool: <%= ENV['FLOATING_IP_POOL'] %>
 private_key_path: <%= ENV['SSH_KEY_FILE'] %>
 require_chef_omnibus: false
 flavor_ref: smem-2vcpu
 image_ref: ad420e91-8da3-4b13-8ff3-3f7aac770711
 username: cloud-user

driver:
  name: vagrant

driver_config:
  network:
    - ["forwarded_port", {guest: 80, host: 8888}]
    - ["forwarded_port", {guest: 8080, host: 8080}]
    - ["forwarded_port", {guest: 443, host: 4443}]
  customize:
    memory: 256
  require_chef_omnibus: false

provisioner:
  name: chef_zero
  chef_omnibus_url: http://www.getchef.com/chef/install.sh

platforms:
- name: trusty-server-cloudimg-amd64
  driver_plugin: openstack
  driver_config:
    image_ref: trusty-server-cloudimg-amd64
    username: ubuntu

- name: rhel6-tgt-cloud-init
  driver_plugin: openstack
  driver_config:
    image_ref: rhel6-tgt-cloud-init
    username: ubuntu

- name: target_rhel_64
  driver:
    name: vagrant
    customize:
      memory: 256
    box: target_rhel_64
    box_url: http://10.63.11.160/vagrant/boxes/target_rhel_64.box

- name: target_ubuntu_1404
  driver:
    name: vagrant
    customize:
      memory: 256
    box: target-ubuntu-1404
    box_url: http://10.63.11.160/vagrant/boxes/opscode_ubuntu-14.04_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[sandbox::default]
    attributes:
